name: Copper

on:
  schedule:
    - cron: '* * * * *'  # Run every minute

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Use the latest version in the v2 major version

    - name: Set up Python
      uses: actions/setup-python@v2  # Use the latest version in the v2 major version
      with:
        python-version: '3'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests selenium beautifulsoup4

    - name: Print Installed Packages
      run: |
        python -m pip list

    - name: Run Copper Script
      run: |
        python copper.py
