name: SkiBot

on:
  schedule:
    - cron: '* * * * *'  # Run every minute

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.5.1

    - name: Set up Python
      uses: actions/setup-python@v2.7.1
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests selenium beautifulsoup4

    - name: Print Installed Packages
      run: |
        python -m pip list

    - name: Run SkiBot Script
      run: |
        python copper.py
