name: Stocks

on:
  schedule:
    - cron: '* * * * *'  # Run every minute

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests selenium beautifulsoup4 requests_html

    - name: Print Installed Packages
      run: |
        python -m pip list

    - name: Run Stocks Script
      run: |
        python FINAL.py
