name: Stocks

on:
  schedule:
    - cron: '0 1 * * *'  # Run @ 1am GMT or 7pm MST

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests gspread oauth2client pandas

    - name: Print Installed Packages
      run: |
        python -m pip list

    - name: Run Stocks Script
      run: |
        python FINAL.py
